<?php
/**
 * EC-FRONTPAGE-READING-001: Honor Settings → Reading.
 * If a REAL converted Page is assigned as the static front page (it has its own
 * page-*.php template and is NOT WPConvert's auto "Home" placeholder), render
 * that page through the normal template hierarchy instead of the baked homepage
 * snapshot below. This lets the site owner pick any page as the homepage.
 */
if ( is_front_page() && 'page' === get_option( 'show_on_front' ) ) {
    $wpc_front_id = (int) get_option( 'page_on_front' );
    if ( $wpc_front_id ) {
        $wpc_tpl  = get_post_meta( $wpc_front_id, '_wp_page_template', true );
        $wpc_body = (string) get_post_field( 'post_content', $wpc_front_id );
        $wpc_is_autogen_home = ( strpos( $wpc_body, 'automatically generated by WPConvert as the homepage' ) !== false );
        if ( ! $wpc_is_autogen_home
            && is_string( $wpc_tpl ) && '' !== $wpc_tpl && 'default' !== $wpc_tpl && 'front-page.php' !== $wpc_tpl
            && file_exists( get_template_directory() . '/' . $wpc_tpl ) ) {
            include get_template_directory() . '/' . $wpc_tpl;
            return;
        }
    }
}
?>
<?php get_header(); ?>
<div id="primary" class="content-area">
  <div id="main-content" data-wpconvert-was-main="true">

<section class="hero" data-wpc-id="wpc_a6e5b6b7ac" data-wpc-editable="section">
  <div class="container hero-grid">
    <div>
      <span class="eyebrow" data-wpc-id="wpc_9f9e136057" data-wpc-editable="text">✓ Pålidelige løsninger til erhverv</span>
      <h1 data-wpc-id="wpc_42d773e41e" data-wpc-editable="heading">Professionel service til et bedre arbejdsmiljø og et velholdt byggeri.</h1>
      <p data-wpc-id="wpc_2a2f4ad6d3" data-wpc-editable="text">STS ApS leverer hurtige og gennemførte løsninger for virksomheder, ejendomme og byggeprojekter – med fokus på kvalitet, sikkerhed og fleksibilitet i hele Danmark.</p>
      <div class="hero-actions">
        <a class="btn btn-primary" href="<?php echo home_url('/kontakt/'); ?>" data-wpc-id="wpc_6e7f81cd39" data-wpc-editable="button">Bestil et gratis tilbud</a>
        <a class="btn btn-secondary" href="<?php echo home_url('/service/'); ?>" data-wpc-id="wpc_ddf696f19d" data-wpc-editable="button">Se alle ydelser</a>
      </div>
    </div>
    <div class="hero-card">
      <img src="<?php echo get_template_directory_uri(); ?>/assets/images/sliderdark-20260811-143051-2c441c.jpg" alt="Professionel servicemedarbejder fra STS ApS i aktion" data-wpc-id="wpc_c6d652e8f1" data-wpc-editable="image">
      <div class="metric-strip" data-wpc-id="wpc_66bf3c95ea" data-wpc-editable="text">
        <div class="metric"><strong>24/7</strong><span>Beredskab</span></div>
        <div class="metric"><strong>100%</strong><span>Fleksibel</span></div>
        <div class="metric"><strong>20+</strong><span>Erfaring</span></div>
        <div class="metric"><strong>2 t</strong><span>Svartid</span></div>
      </div>
    </div>
  </div>
</section>

<section class="section section-tinted active" data-wpc-id="wpc_e0885fd91b" data-wpc-editable="section">
  <div class="container">
    <div class="section-head">
      <div>
        <span class="eyebrow" data-wpc-id="wpc_9f043d651f" data-wpc-editable="text">Vores serviceunivers</span>
        <h2 data-wpc-id="wpc_6d40fc003d" data-wpc-editable="heading">Tre stærke spor. En samlet partner.</h2>
      </div>
      <p data-wpc-id="wpc_5701505c7b" data-wpc-editable="text">Alle ydelser er samlet i STS Byg, STS Mal og STS Ren, så I hurtigt kan finde den rette løsning.</p>
    </div>
    <div class="pillar-grid" data-pillar-list-root="" data-path-prefix="">
      <article class="pillar-card pillar-byg" data-pillar-card-category="byg">
        <div class="pillar-head">
          <span class="pillar-icon">🏗️</span>
          <h3 data-wpc-id="wpc_e476499724" data-wpc-editable="heading">STS Byg</h3>
        </div>
        <p data-wpc-id="wpc_d195ff5422" data-wpc-editable="text">Til byggepladser, nedrivning og praktisk bemanding med fokus på sikker drift og fremdrift.</p>
        <a class="pillar-cta" data-pillar-category-link="byg" href="<?php echo home_url('/sts-byg/'); ?>" data-wpc-id="wpc_607aaebbef" data-wpc-editable="button">Se STS Byg</a>
      </article>

      <article class="pillar-card pillar-mal" data-pillar-card-category="mal">
        <div class="pillar-head">
          <span class="pillar-icon">🎨</span>
          <h3 data-wpc-id="wpc_9fb4640e6c" data-wpc-editable="heading">STS Mal</h3>
        </div>
        <p data-wpc-id="wpc_2fe1cc0e9a" data-wpc-editable="text">Til opfriskning, finish og løbende vedligehold med professionelle maler- og håndværksløsninger.</p>
        <a class="pillar-cta" data-pillar-category-link="mal" href="<?php echo home_url('/sts-mal/'); ?>" data-wpc-id="wpc_cfbfaf2b93" data-wpc-editable="button">Se STS Mal</a>
      </article>

      <article class="pillar-card pillar-ren" data-pillar-card-category="ren">
        <div class="pillar-head">
          <span class="pillar-icon">🫧</span>
          <h3 data-wpc-id="wpc_e8d7c7c18a" data-wpc-editable="heading">STS Ren</h3>
        </div>
        <p data-wpc-id="wpc_7d71e7b989" data-wpc-editable="text">Til daglig drift, rengøring og ejendomspleje med stabile aftaler og synlig kvalitet.</p>
        <a class="pillar-cta" data-pillar-category-link="ren" href="<?php echo home_url('/sts-ren/'); ?>" data-wpc-id="wpc_d2ec5de8fa" data-wpc-editable="button">Se STS Ren</a>
      </article>
    </div>
  </div>
</section>

<section class="section" data-wpc-id="wpc_a1cec1a23c" data-wpc-editable="section">
  <div class="container">
    <div class="section-head">
      <div>
        <span class="eyebrow" data-wpc-id="wpc_452592d61d" data-wpc-editable="text">Hvorfor vælge STS</span>
        <h2 data-wpc-id="wpc_4c2bcf6e37" data-wpc-editable="heading">En moderne partner med stærk servicekultur og høj tillid.</h2>
      </div>
    </div>
    <div class="grid trust-grid">
      <article class="feature-card">
        <h3 data-wpc-id="wpc_f2c925e60f" data-wpc-editable="heading">✅ Certificeret og sikker</h3>
        <p data-wpc-id="wpc_ef1ad476bd" data-wpc-editable="text">Vi arbejder efter klare standarder for sikkerhed, arbejdsmiljø og dokumentation – INSTA 800 certificeret.</p>
      </article>
      <article class="feature-card">
        <h3 data-wpc-id="wpc_60859b714f" data-wpc-editable="heading">⚡ Hurtig reaktion</h3>
        <p data-wpc-id="wpc_5b56cf7651" data-wpc-editable="text">Vi er tilgængelige til eksisterende kunder og kan håndtere akutte behov med kort varsel.</p>
      </article>
      <article class="feature-card">
        <h3 data-wpc-id="wpc_604e7d2db2" data-wpc-editable="heading">📋 Præcis projektstyring</h3>
        <p data-wpc-id="wpc_2e6a459d65" data-wpc-editable="text">Fra planlægning til udførelse følger vi op på detaljer og deadlines. Altid med en klar kontaktperson.</p>
      </article>
      <article class="feature-card">
        <h3 data-wpc-id="wpc_b53a305ef3" data-wpc-editable="heading">💬 Transparent kommunikation</h3>
        <p data-wpc-id="wpc_ed1fa1ca06" data-wpc-editable="text">Du får tydelig status, klare aftaler og direkte adgang til dit projektteam gennem hele forløbet.</p>
      </article>
    </div>
  </div>
</section>

<section class="section" data-wpc-id="wpc_9a86a2d04f" data-wpc-editable="section">
  <div class="container">
    <div class="quote-band">
      <p data-wpc-id="wpc_593a96010a" data-wpc-editable="text">„Fleksibilitet, højt serviceniveau og det gode tilhørsforhold er grundstenen i vores arbejde. Vi er ikke en leverandør – vi er en partner.“</p>
      <strong data-wpc-id="wpc_473171d16c" data-wpc-editable="text">— Kristina Josty, Planlægger og administrationschef</strong>
    </div>
  </div>
</section>

<section class="section section-tinted" data-wpc-id="wpc_7e85f5d6d5" data-wpc-editable="section">
  <div class="container">
    <div class="section-head">
      <div>
        <span class="eyebrow" data-wpc-id="wpc_5c0c39b8d4" data-wpc-editable="text">Kundernes ord</span>
        <h2 data-wpc-id="wpc_5eaeaeee92" data-wpc-editable="heading">Det siger vores kunder om samarbejdet.</h2>
      </div>
    </div>
    <div class="grid card-grid">
      <article class="testimonial-card">
        <p data-wpc-id="wpc_6ec02622e3" data-wpc-editable="text">„STS kom hurtigt ind i projektet og løste opgaven uden unødvendig bureaukrati. Det føles som et stærkt og stabilt samarbejde.“</p>
        <div class="testimonial-meta">
          <div>
            <div class="testimonial-stars" data-wpc-id="wpc_7a4d5873c9" data-wpc-editable="text">★★★★★</div>
            <strong data-wpc-id="wpc_cf0aeef508" data-wpc-editable="text">Lars M., Driftschef</strong>
            <span data-wpc-id="wpc_3bb8c790ec" data-wpc-editable="text">Industrivirksomhed, København</span>
          </div>
        </div>
      </article>
      <article class="testimonial-card">
        <p data-wpc-id="wpc_a7be0e7ce0" data-wpc-editable="text">„Vi sætter stor pris på deres fokus på detaljer og deres evne til altid at være tilgængelige, når det virkelig gælder.“</p>
        <div class="testimonial-meta">
          <div>
            <div class="testimonial-stars" data-wpc-id="wpc_a562fd0a94" data-wpc-editable="text">★★★★★</div>
            <strong data-wpc-id="wpc_f2094c33c7" data-wpc-editable="text">Hanne P., Ejendomsadministrator</strong>
            <span data-wpc-id="wpc_b3e1c09250" data-wpc-editable="text">Boligselskab, Aarhus</span>
          </div>
        </div>
      </article>
      <article class="testimonial-card">
        <p data-wpc-id="wpc_ed64e78324" data-wpc-editable="text">„Fra første samtale til afslutning var kommunikationen tydelig og præcis. Vi vil absolut bruge dem igen.“</p>
        <div class="testimonial-meta">
          <div>
            <div class="testimonial-stars" data-wpc-id="wpc_11e780faec" data-wpc-editable="text">★★★★★</div>
            <strong data-wpc-id="wpc_fefe161074" data-wpc-editable="text">Peter K., Byggeleder</strong>
            <span data-wpc-id="wpc_99106f2816" data-wpc-editable="text">Entreprisenør, Odense</span>
          </div>
        </div>
      </article>
    </div>
  </div>
</section>

<section class="cta-band" data-wpc-id="wpc_2f229aa0f0" data-wpc-editable="section">
  <div class="container">
    <h2 data-wpc-id="wpc_67cc02e66a" data-wpc-editable="heading">Klar til at komme i gang?</h2>
    <p data-wpc-id="wpc_ded58b7f18" data-wpc-editable="text">Få et gratis og uforpligtende tilbud. Vi svarer inden for en arbejdsdag.</p>
    <div class="cta-actions">
      <a class="btn-white" href="<?php echo home_url('/kontakt/'); ?>" data-wpc-id="wpc_2d97474d1b" data-wpc-editable="button">Kontakt os i dag</a>
      <a class="btn-outline-white" href="<?php echo home_url('/service/'); ?>" data-wpc-id="wpc_dabe49f311" data-wpc-editable="button">Se vores ydelser</a>
    </div>
  </div>
</section>
    </div>
</div>
<?php get_footer(); ?>
